---
title: Thomas' _Cajita_ Project
theme: lumen
---

## A picture of my _cajita_


### Mimi, Seymour Glass, & a little wooden bear
  - The saddest, most sympathetic stuffed dog in the world & his bear
  - Mimi used to hand sew my halloween costumes: a big orange felt pumpkin & Bugs Bunny with big stuffed carrots
  - She taught me unconditional love, kindness to strangers, and how you should stand up for yourself
    
### My mom & her notes
  - My mom used to write me notes every time I came home from college
  - She taught me 

### My dad, golf, & juggling
  - I remember watching my dad juggle three beanie babies when I was a kid, completely mesmerized
  - My dad was in his element on the golf course
  - He knew everyone's name and always greeted them with a hand shake and a laugh

### Margaret 
  - My sister is one of the nicest people to walk this green earth
  - I am lucky to have her on my team
  - Forever a shoulder to lean on and an ear to listen

### Science, curiosity, & who I wanna be
  - I don't know if I totally know what kind of scientist I want to be
    - I want to always learn
    - I want to work with others and teach
  - But I think I know the kind of person that I want to be
    - And that is thanks to the wonderful people that I am lucky to call friends and family
  
  